### ISSUE TITLE
Hardware V2 wiring diagram element AM2D-0512DZ

### ISSUE THREAD

**Issue by michalwoz** [ingof/smi-tools#1]
I'm gathering elements for RS232 TTL <> SMI interface. On http://smiwiki.thefischer.net hardware V2 there is AM2D-0512DZ. We need 24V and AM2D-05**12**DZ is "dual output", so we actually have 24V using V- and V+ of AM2D-05**12**DZ.

So wiring diagram is CORRECT!

May be it is worth to mention that we can use AM2D-0524SZ SINGLE output? Can we?

**Comment by ingof** [comment]
Yes, thnx

That is wrong. I will fix it asap. It should be a 5V to 24V converter.

**Comment by michalwoz** [comment]
@ingof I've updated my opening post in this issue. The DC DC converter seems to be OK. AM2D-0512DZ is 12V, but DUAL output.
At first look i thought that AM2D-0512DZ voltage is wrong, but both outputs are used.
Update your reply not to mislead someone, please.
Sorry for confusion.

**Comment by ingof** [comment]
It would be better to use the Single output version (AM2D-0524SZ) because it has a 4% better efficiency.

I built this circuit a long time ago.
You need any 5 to 24V DC converter.
I cant get a the desired DC converter and choosed what i can get at moment.
It was the dual output version and used both to get 24V DC.
